<a href="https://colab.research.google.com/github/Hwarriach/Numpy-Mini-Project/blob/main/Census_decoded.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Importing & Loading Data

data_file = 'makeSenseOfCensus.csv'
import numpy as np

In [ ]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [ ]:
data.shape

(1000, 8)

In [ ]:
## Append the Data

new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
new_data = np.concatenate((data,new_record),axis=0)
print(new_data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [ ]:
new_data.shape

(1001, 8)

In [ ]:
## New Age Array

age = new_data[:,0]
print(age)

array([39., 50., 38., ..., 40., 39., 50.])

In [ ]:
## Max Age

max_age = age.max()
print(max_age)

90.0


In [ ]:
## Min Age

min_age = age.min()
print(min_age)

17.0


In [ ]:
## Avg Age

age_mean = age.mean()
print(age_mean)

38.06293706293706


In [ ]:
## Age Standard Deviation 

age_std = age.std()
print(age_std)

13.341478176165857


In [ ]:
## Subset arrays of Race

race = new_data[:,2]
race_0 = race[race==0]
race_1 = race[race==1]
race_2 = race[race==2]
race_3 = race[race==3]
race_4 = race[race==4]
print(race_0)
print(race_1)
print(race_2)
print(race_3)
print(race_4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4

In [ ]:
## Lenght of each Race array

len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

print(len_0)
print(len_1)
print(len_2)
print(len_3)
print(len_4)


10
27
110
6
848


In [ ]:
## Race with the least number of citizens

x = [len_0, len_1, len_2, len_3, len_4]
x1 = np.array(x) 
print(x1.min())
print(np.argwhere(x1==6))

6
[[3]]


In [ ]:
minority_race = 3

In [ ]:
## Number of Senior Citizens

senior_citizen = age[age>60]
senior_citizens_len = len(senior_citizen)
print(senior_citizens_len)

61


In [ ]:
## Average working Total

working_hours = new_data[:,6]
working_hours_sum = np.sum(working_hours[age>60])
print(working_hours_sum)

1917.0


In [ ]:
## Avg working hours for Senior Citizens

avg_working_hours = working_hours_sum / senior_citizens_len
print(avg_working_hours)

31.42622950819672


In [ ]:
## Checking if govt policy is followed in regards to max hours that senior citizens can work

if avg_working_hours <= 25:
  print("govt policy is followed")
else:
  print("govt policy not followed")

govt policy not followed


In [ ]:
## Number of lower/higher earners based on education level

high_ed = new_data[:,1]
high = high_ed[high_ed > 10]

low = high_ed[high_ed <= 10]

print(len(high))
print(len(low))

327
674


In [ ]:
## Avg Pay

income = new_data[:,7]
avg_pay_high = np.mean(income[high_ed > 10])
avg_pay_low = np.mean(income[high_ed <= 10])

print(avg_pay_high)
print(avg_pay_low)

0.42813455657492355
0.13649851632047477
